# Generated by Django 5.2 on 2025-05-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0002_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
