# Generated by Django 5.2 on 2025-06-06 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='choice_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='souka.choice')),
            ],
        ),
    ]
