# Generated by Django 5.2 on 2025-06-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0006_choiceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='souka.chapter'),
        ),
    ]
