# Generated by Django 5.2 on 2025-06-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0007_alter_choice_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='souka.chapter'),
        ),
    ]
