# Generated by Django 5.2 on 2025-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0009_remove_chapterprogress_choice_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='words_learned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
