# Generated by Django 5.2 on 2025-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0010_chapterprogress_words_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='correct_answers',
            field=models.TextField(blank=True, null=True, verbose_name='Правильные ответы (через запятую)'),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(verbose_name='Иероглиф'),
        ),
    ]
