# Generated by Django 5.2 on 2025-06-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0011_text_correct_answers_alter_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='test_done',
            field=models.BooleanField(default=False),
        ),
    ]
