# Generated by Django 5.2 on 2025-06-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0012_chapterprogress_test_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='text_perfect',
            field=models.BooleanField(default=False),
        ),
    ]
