# Generated by Django 5.2 on 2025-06-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souka', '0013_chapterprogress_text_perfect'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterprogress',
            name='choice_1_perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='choice_2_perfect',
            field=models.BooleanField(default=False),
        ),
    ]
